### ISSUE TITLE
请问怎么在unraid里安装呢？

### ISSUE THREAD

**Issue by fireflycao** [roylez/subfinder#1]
新手，多谢指导！

**Comment by roylez** [comment]
直接用`roylez/subs`这个docker镜像就好了，把你放媒体的目录，映射到容器里的`/data`就好。

**Comment by fireflycao** [comment]
多谢！请问下面的设置对吗？
![image](https://user-images.githubusercontent.com/20470524/122726794-edbf2d80-d2a8-11eb-9e0d-559933dc17a3.png)

**Comment by fireflycao** [comment]
conf这样设置？
![image](https://user-images.githubusercontent.com/20470524/122727693-e2b8cd00-d2a9-11eb-8459-c90337584ffd.png)

**Comment by fireflycao** [comment]
已有字幕的nfo文件会被跳过？
请问是nfo文件里面显示有字幕，还是文件夹里存在*.srt或者其他字幕文件？
tinyMediaManager抓取的nfo文件。从rarbg下载的电影现在都有一个sub文件夹，里面有字幕。nfo文件里认为有字幕。

**Comment by fireflycao** [comment]
不知道哪里错误，自动停止。
![image](https://user-images.githubusercontent.com/20470524/122732605-07637380-d2af-11eb-88d2-e0ba4a0ed5e5.png)
I, [2021-06-21 08:30:53#1] INFO -- : ....................启动 SUBS
I, [2021-06-21 08:30:55#1] INFO -- : 电影 [1917], imdb: tt8579674, 已有 1 个字幕
I, [2021-06-21 08:30:55#1] INFO -- : 电影 [双龙出手], imdb: tt1272878, 已有 1 个字幕
I, [2021-06-21 08:30:55#1] INFO -- : 电影 [2067], imdb: tt1918734
/usr/lib/ruby/2.7.0/net/http.rb:960:in `initialize': Failed to open TCP connection to zmk.pw:80 (getaddrinfo: Try again) (SocketError)

from /usr/lib/ruby/2.7.0/net/http.rb:960:in `open'
from /usr/lib/ruby/2.7.0/net/http.rb:960:in `block in connect'
from /usr/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
from /usr/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
from /usr/lib/ruby/2.7.0/net/http.rb:958:in `connect'
from /usr/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
from /usr/lib/ruby/2.7.0/net/http.rb:938:in `start'
from /usr/lib/ruby/gems/2.7.0/gems/net-http-persistent-4.0.1/lib/net/http/persistent.rb:655:in `start'
from /usr/lib/ruby/gems/2.7.0/gems/net-http-persistent-4.0.1/lib/net/http/persistent.rb:595:in `connection_for'
from /usr/lib/ruby/gems/2.7.0/gems/net-http-persistent-4.0.1/lib/net/http/persistent.rb:885:in `request'
from /usr/lib/ruby/gems/2.7.0/gems/mechanize-2.7.7/lib/mechanize/http/agent.rb:280:in `fetch'
from /usr/lib/ruby/gems/2.7.0/gems/mechanize-2.7.7/lib/mechanize.rb:464:in `get'
from ./subs.rb:24:in `find'
from ./subs.rb:167:in `block in process'
from ./subs.rb:166:in `each'
from ./subs.rb:166:in `reduce'
from ./subs.rb:166:in `process'
from ./subs.rb:295:in `block in run_finder'
from ./subs.rb:294:in `each'
from ./subs.rb:294:in `run_finder'
from ./subs.rb:343:in `<main>'
/usr/lib/ruby/2.7.0/net/http.rb:960:in `initialize': getaddrinfo: Try again (SocketError)
from /usr/lib/ruby/2.7.0/net/http.rb:960:in `open'
from /usr/lib/ruby/2.7.0/net/http.rb:960:in `block in connect'
from /usr/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
from /usr/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
from /usr/lib/ruby/2.7.0/net/http.rb:958:in `connect'
from /usr/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
from /usr/lib/ruby/2.7.0/net/http.rb:938:in `start'
from /usr/lib/ruby/gems/2.7.0/gems/net-http-persistent-4.0.1/lib/net/http/persistent.rb:655:in `start'
from /usr/lib/ruby/gems/2.7.0/gems/net-http-persistent-4.0.1/lib/net/http/persistent.rb:595:in `connection_for'
from /usr/lib/ruby/gems/2.7.0/gems/net-http-persistent-4.0.1/lib/net/http/persistent.rb:885:in `request'
from /usr/lib/ruby/gems/2.7.0/gems/mechanize-2.7.7/lib/mechanize/http/agent.rb:280:in `fetch'
from /usr/lib/ruby/gems/2.7.0/gems/mechanize-2.7.7/lib/mechanize.rb:464:in `get'
from ./subs.rb:24:in `find'
from ./subs.rb:167:in `block in process'
from ./subs.rb:166:in `each'
from ./subs.rb:166:in `reduce'
from ./subs.rb:166:in `process'
from ./subs.rb:295:in `block in run_finder'
from ./subs.rb:294:in `each'
from ./subs.rb:294:in `run_finder'
from ./subs.rb:343:in `<main>'

**Comment by fireflycao** [comment]
又一次
I, [2021-06-21 08:46:08#1] INFO -- : 电影 [暗网：蝉3301], imdb: tt8110246
I, [2021-06-21 08:46:09#1] INFO -- 字幕库: ---- http://zmk.pw/subs/56434.html
I, [2021-06-21 08:46:09#1] INFO -- 字幕库: 找到 'Dark Web Cicada 3301.2021.1080p.Bluray.DTS-HD.MA.5.1.X264-EVO.srt', 下载量 2488
I, [2021-06-21 08:46:10#1] INFO -- : 重命名 [zmk.pw]Dark Web Cicada 3301.2021.1080p.Bluray.DTS-HD.MA.5.1.X264-EVO.srt
I, [2021-06-21 08:46:10#1] INFO -- : -> Dark.Web.Cicada.3301.2021.1080p.BluRay.H264.AAC-RARBG.srt
I, [2021-06-21 08:46:10#1] INFO -- : 电影 [死人的复仇], imdb: tt2101341, 已有 1 个字幕
I, [2021-06-21 08:46:10#1] INFO -- : 电影 [亲爱的同志], imdb: tt10796286, 已有 1 个字幕
I, [2021-06-21 08:46:10#1] INFO -- : 电影 [再也不见 2020], imdb: tt13567480, 已有 2 个字幕
I, [2021-06-21 08:46:10#1] INFO -- : 电影 [鹿皮], imdb: tt8193790, 已有 1 个字幕
I, [2021-06-21 08:46:11#1] INFO -- : 电影 [玩命三姐妹], imdb: tt1545304, 已有 1 个字幕
I, [2021-06-21 08:46:11#1] INFO -- : 电影 [唐人街探案3], imdb: tt10370822, 已有 1 个字幕
I, [2021-06-21 08:46:11#1] INFO -- : 电影 [多力特的奇幻冒险], imdb: tt6673612, 已有 1 个字幕
I, [2021-06-21 08:46:11#1] INFO -- : 电影 [异界之门], imdb: tt12483708, 已有 2 个字幕
I, [2021-06-21 08:46:11#1] INFO -- : 电影 [每况愈下], imdb: tt4558376, 已有 1 个字幕
I, [2021-06-21 08:46:11#1] INFO -- : 电影 [唐顿庄园], imdb: tt6398184, 已有 2 个字幕
I, [2021-06-21 08:46:11#1] INFO -- : 电影 [梦工厂], imdb: tt8157074, 已有 2 个字幕
I, [2021-06-21 08:46:11#1] INFO -- : 电影 [梦乡], imdb: tt5294522, 已有 2 个字幕
./subs.rb:182:in `read_nfo': undefined method `text' for nil:NilClass (NoMethodError)
from ./subs.rb:164:in `process'
from ./subs.rb:295:in `block in run_finder'
from ./subs.rb:294:in `each'
from ./subs.rb:294:in `run_finder'
from ./subs.rb:343:in `<main>'

**Comment by roylez** [comment]
你有一部电影，nfo里面没有imdb的号码，我不知道是哪部。我今天有空试试看能不能解决这种没有imdb号的，不行就跳过。

**Comment by fireflycao** [comment]
非常好用软件，谢谢了！昨天我试过拷走 [梦乡]的下一部，可以往后跑一些，我的电影库500多部，总是有些不完全规范的命名。跳过是个好主意。在log输出错误的文件名应该也可以。方便查找，现在我只能猜下是卡住的名称排序的下一部。

**Comment by roylez** [comment]
已经修复。你可以更新下docker镜像。

现在做法是跳过，因为imdb都没代号的电影我实在想不出有什么必要去看。如果是imdb有代号只是nfo的问题，那就应该是在nfo那边处理。

**Comment by fireflycao** [comment]
, [2021-06-22 00:49:06#1] WARN -- : 电影 [浴血无名川], imdb: 未知，略过
W, [2021-06-22 00:49:06#1] WARN -- : 电影 [4K hevc 10bit演示片 极致的4K演示片 | 4K测试用], imdb: 未知，略过
I, [2021-06-22 00:49:06#1] INFO -- : 电影 [特洛伊], imdb: tt0332452
I, [2021-06-22 00:49:10#1] INFO -- 字幕库: ---- http://zmk.pw/subs/24148.html
I, [2021-06-22 00:49:12#1] INFO -- 字幕库: 找到 '特洛伊：木马屠城 Troy (2004) 导演剪辑版 196分钟 蓝光原盘官方繁体中文字幕 时长03:16:02', 下载量 9608
./subs.rb:70:in `join': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
from ./subs.rb:70:in `download'
from ./subs.rb:168:in `block in process'
from ./subs.rb:166:in `each'
from ./subs.rb:166:in `reduce'
from ./subs.rb:166:in `process'
from ./subs.rb:299:in `block in run_finder'
from ./subs.rb:298:in `each'
from ./subs.rb:298:in `run_finder'
from ./subs.rb:347:in `<main>'

![image](https://user-images.githubusercontent.com/20470524/122846243-032f6880-d338-11eb-9141-2dcb7fd8ed8f.png)
这个是蓝光原盘，规则里能否跳过？

**Comment by fireflycao** [comment]
还是nfo的原因吗？
有个浴血无名川。还真没有imdb，网络电影

**Comment by fireflycao** [comment]
请问容器的config是什么路径？/conf还是/config

**Comment by roylez** [comment]
现在没有config。只有几个环境变量可以设置，都在 readme 里面。

**Comment by fireflycao** [comment]
好的，多谢！

**Comment by fireflycao** [comment]
把蓝光原盘删掉，完整走完一边！多谢啦，以后只要把电影下完字幕就自动找了，再次感谢。要是能加入扫描时排除的文件夹变量就好了。
I, [2021-06-22 03:32:59#1] INFO -- : 电影 [见证9/11：在世贸中心遗址的阴影下], imdb: tt13091122
I, [2021-06-22 03:33:02#1] INFO -- 字幕库: 未找到字幕
I, [2021-06-22 03:33:02#1] INFO -- SUBHD: 未找到字幕
I, [2021-06-22 03:33:02#1] INFO -- : 电影 [神力女超人1984], imdb: tt7126948, 已有 2 个字幕
I, [2021-06-22 03:33:02#1] INFO -- : 电影 [浴室墙上的字], imdb: tt8045906, 已有 1 个字幕
I, [2021-06-22 03:33:02#1] INFO -- : 电影 [人之怒], imdb: tt11083552, 已有 2 个字幕
I, [2021-06-22 03:33:02#1] INFO -- : 电影 [致命弯道7], imdb: tt9110170, 已有 1 个字幕
I, [2021-06-22 03:33:02#1] INFO -- : 电影 [小美], imdb: tt7996560, 已有 1 个字幕
I, [2021-06-22 03:33:02#1] INFO -- : 电影 [黑道与家族], imdb: tt13356884, 已有 1 个字幕
I, [2021-06-22 03:33:02#1] INFO -- : 电影 [有求必应日], imdb: tt8521876, 已有 1 个字幕
I, [2021-06-22 03:33:02#1] INFO -- : 电影 [昨日奇迹], imdb: tt8079248, 已有 4 个字幕
W, [2021-06-22 03:33:02#1] WARN -- : 电影 [浴血无名川], imdb: 未知，略过
W, [2021-06-22 03:33:02#1] WARN -- : 电影 [4K hevc 10bit演示片 极致的4K演示片 | 4K测试用], imdb: 未知，略过
I, [2021-06-22 03:33:02#1] INFO -- : 电影 [地球改变之年], imdb: tt14372240, 已有 2 个字幕
I, [2021-06-22 03:33:02#1] INFO -- : 电影 [两只老虎], imdb: tt10333606, 已有 1 个字幕
I, [2021-06-22 03:33:02#1] INFO -- : 电影 [只有芸知道], imdb: tt10564446
I, [2021-06-22 03:33:06#1] INFO -- 字幕库: 未找到字幕
I, [2021-06-22 03:33:07#1] INFO -- SUBHD: 未找到字幕
I, [2021-06-22 03:33:07#1] INFO -- : 电影 [吹哨人], imdb: tt8971476, 已有 1 个字幕
I, [2021-06-22 03:33:07#1] INFO -- : 电影 [囧妈], imdb: tt11172926
I, [2021-06-22 03:33:07#1] INFO -- SUBHD: 未找到字幕
I, [2021-06-22 03:33:07#1] INFO -- : 电影 [吹哨人], imdb: tt8971476, 已有 1 个字幕
I, [2021-06-22 03:33:07#1] INFO -- : 电影 [囧妈], imdb: tt11172926
I, [2021-06-22 03:33:12#1] INFO -- 字幕库: 未找到字幕
I, [2021-06-22 03:33:12#1] INFO -- 字幕库: 未找到字幕
I, [2021-06-22 03:33:12#1] INFO -- SUBHD: 未找到字幕
I, [2021-06-22 03:33:12#1] INFO -- : 电影 [少年的你], imdb: tt9586294, 已有 1 个字幕
I, [2021-06-22 03:33:12#1] INFO -- : 电影 [阳光灿烂的日子], imdb: tt0111786, 已有 1 个字幕
I, [2021-06-22 03:33:12#1] INFO -- : ....................一共运行 249.14 秒

**Comment by roylez** [comment]
你说的有问题的那个蓝光，其实是字幕库的文件名非utf-8造成的。我已经修复了。你过几分钟再更新下docker镜像就好。

**Comment by fireflycao** [comment]
回头我再下个原盘测试下。



在 2021年6月22日 11:43，Roy Zuo ***@***.***>写道：

你说的有问题的那个蓝光，其实是字幕库的文件名非utf-8造成的。我已经修复了。你过几分钟再更新下docker镜像就好。

**Comment by fireflycao** [comment]
已经正常定期搜索字幕，多谢！
