### ISSUE TITLE
您好，又有错误信息

### ISSUE THREAD

**Issue by fireflycao** [roylez/subfinder#2]
`/usr/lib/ruby/2.7.0/net/http.rb:960:in `initialize': Failed to open TCP connection to zmk.pw:80 (Operation timed out - connect(2) for "zmk.pw" port 80) (Errno::ETIMEDOUT)

from /usr/lib/ruby/2.7.0/net/http.rb:960:in `open'
from /usr/lib/ruby/2.7.0/net/http.rb:960:in `block in connect'
from /usr/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
from /usr/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
from /usr/lib/ruby/2.7.0/net/http.rb:958:in `connect'
from /usr/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
from /usr/lib/ruby/2.7.0/net/http.rb:938:in `start'
from /usr/lib/ruby/gems/2.7.0/gems/net-http-persistent-4.0.1/lib/net/http/persistent.rb:655:in `start'
from /usr/lib/ruby/gems/2.7.0/gems/net-http-persistent-4.0.1/lib/net/http/persistent.rb:595:in `connection_for'
from /usr/lib/ruby/gems/2.7.0/gems/net-http-persistent-4.0.1/lib/net/http/persistent.rb:885:in `request'
from /usr/lib/ruby/gems/2.7.0/gems/mechanize-2.7.7/lib/mechanize/http/agent.rb:280:in `fetch'
from /usr/lib/ruby/gems/2.7.0/gems/mechanize-2.7.7/lib/mechanize.rb:464:in `get'
from ./subs.rb:25:in `find'
from ./subs.rb:196:in `block in process'
from ./subs.rb:195:in `each'
from ./subs.rb:195:in `reduce'
from ./subs.rb:195:in `process'
from ./subs.rb:328:in `block in run_finder'
from ./subs.rb:327:in `each'
from ./subs.rb:327:in `run_finder'
from ./subs.rb:376:in `<main>'`

**Comment by roylez** [comment]
其实这个我知道。

问题在于字幕库时不时抽风导致请求超时。确实可以稍作处理让这种情况不要丢很多错误信息出来，但是一直忙別的事情懒得去管。因为大家都是在docker里面跑，只要加上`restart: always`就会自动重新启动container，所以也不是太大的问题。一旦字幕库又能连上，就又可以自动下载字幕了，不会影响使用。

我哪天有空再处理下。

**Comment by fireflycao** [comment]
谢了，请问是加在“Container Variable”里吗？
![image](https://user-images.githubusercontent.com/20470524/125006456-c631d880-e090-11eb-86cb-dc4352b04f23.png)

**Comment by roylez** [comment]
unraid没用过。所以我也不知道怎么加

**Comment by fireflycao** [comment]
等您更新了。

**Comment by fireflycao** [comment]
下面两个电影，找到字幕包，下载字幕包后未解压。
I, [2021-07-09 10:50:36#1] INFO -- : 电影 [寂静之地], imdb: tt6644200
I, [2021-07-09 10:50:45#1] INFO -- 字幕库: ---- http://zmk.pw/subs/46455.html
I, [2021-07-09 10:50:48#1] INFO -- 字幕库: 找到 '寂静之地(简繁英双语字幕-yyets字幕组)a.quiet.place.2018.1080p.bluray.x264-sparks.zip', 下载量 4.6万
I, [2021-07-09 10:50:57#1] INFO -- : 电影 [寂静之地2], imdb: tt8332922
I, [2021-07-09 10:50:57#1] INFO -- : 电影 [寂静之地2], imdb: tt8332922
I, [2021-07-09 10:51:05#1] INFO -- 字幕库: ---- http://zmk.pw/subs/57791.html
I, [2021-07-09 10:51:09#1] INFO -- 字幕库: 找到 '寂静之地2(简繁字幕)A.Quiet.Place.Part.II.2020.1080p.WEB.H264-NOGRP.zip', 下载量 1.5万

**Comment by roylez** [comment]
后面这个我知道，大概有两种原因：

1. 字幕文件名已经符合格式，不需要更改。我刚刚更新了下，现在这种会有提醒。你这两个字幕文件都是这种情况。
2. 解压缩出来的字幕格式是sup格式。这种很少见，而且sup格式在我用的不论是infuse或是jellyfin上面都不支持。如果改代码跳过sup格式字幕逻辑又稍麻烦，所以也一直没管它。

**Comment by fireflycao** [comment]
好的，多谢！restart: always代码已经加入了吗？我试的unraid设置都没起作用。另外我的log日志显示的应该是伦敦时间。

**Comment by roylez** [comment]
`restart: always`是写docker container的启动参数的。

至于时区，我刚刚给加了改时区支持，加个`TZ=Asia/Shanghai`就是中国时区。不过现在已经默认中国时区了。

**Comment by roylez** [comment]
刚刚发现docker镜像里的7z的`-i`参数好像有问题导致不解压缩，已经去掉了。

**Comment by fireflycao** [comment]
多谢更新！
刚下载试过，有些原本不解压的已经解压，还有个别的没解压。
`I, [2021-07-11 05:33:07#1] INFO -- : 电影 [遗落战境], imdb: tt1483013, 已有 1 个字幕
I, [2021-07-11 05:33:07#1] INFO -- : 电影 [占领2], imdb: tt8615822
I, [2021-07-11 05:33:08#1] INFO -- 字幕库: ---- http://zmk.pw/subs/57613.html
I, [2021-07-11 05:33:08#1] INFO -- 字幕库: 找到 '‎占领2(英字幕)[2.08.17]‎Occupation.Rainfall.2020.1080p.BluRay.x265-RARBG', 下载量 1193
I, [2021-07-11 05:33:09#1] INFO -- : 电影 [官方机密], imdb: tt5431890, 已有 1 个字幕`
![image](https://user-images.githubusercontent.com/20470524/125177229-99a2cb80-e20c-11eb-9347-f4d9ea65db2e.png)

`I, [2021-07-11 05:34:40#1] INFO -- : 电影 [死里逃生], imdb: tt12528166
I, [2021-07-11 05:34:41#1] INFO -- 字幕库: ---- http://zmk.pw/subs/58017.html
I, [2021-07-11 05:34:41#1] INFO -- 字幕库: ---- http://zmk.pw/subs/58017.html
I, [2021-07-11 05:34:41#1] INFO -- 字幕库: 找到 '死里逃生.Out.of.Death.2021.1080p.WEBRip.DD5.1.x264-CM.rar', 下载量 435
I, [2021-07-11 05:34:43#1] INFO -- : 电影 [末日激战], imdb: tt10451914, 已有 1 个字幕`
![image](https://user-images.githubusercontent.com/20470524/125177086-aa9f0d00-e20b-11eb-99bf-19340bd6d76e.png)
`I, [2021-07-11 05:39:38#1] INFO -- : 电影 [绅士们], imdb: tt8367814, 已有 1 个字幕
I, [2021-07-11 05:39:38#1] INFO -- : 电影 [影子写手], imdb: tt1139328
I, [2021-07-11 05:39:39#1] INFO -- 字幕库: ---- http://zmk.pw/subs/26223.html
I, [2021-07-11 05:39:40#1] INFO -- 字幕库: 找到 '影子写手(简英双语) The.Ghost.Writer.2010.1080p.BluRay.X264.DTS-SiHD', 下载量 5520
I, [2021-07-11 05:39:40#1] INFO -- 字幕库: 找到 '影子写手(简英双语) The.Ghost.Writer.2010.1080p.BluRay.X264.DTS-SiHD', 下载量 5520
I, [2021-07-11 05:39:42#1] INFO -- : 电影 [上帝委员会], imdb: tt6852526, 已有 1 个字幕`
![image](https://user-images.githubusercontent.com/20470524/125177169-2a2cdc00-e20c-11eb-9186-d37825f7ebdf.png)

**Comment by roylez** [comment]
rar不能解压缩是我上个commit的错误，删掉了一个字母搞得不执行了。7z以前没料到会有人用，现在已经支持了。

你再试试？

**Comment by fireflycao** [comment]
*.7z和*.rar均已解压，完美，辛苦了！
I, [2021-07-11 18:57:39#1] INFO -- : 电影 [阳光灿烂的日子], imdb: tt0111786, 已有 1 个字幕
I, [2021-07-11 18:57:39#1] INFO -- : ....................一共运行 1502.52 秒

**Comment by fireflycao** [comment]
这个是没自动重命名
`I, [2021-07-11 18:54:19#1] INFO -- : 电影 [激情沸点], imdb: tt0099797
I, [2021-07-11 18:54:20#1] INFO -- 字幕库: ---- http://zmk.pw/subs/29118.html
I, [2021-07-11 18:54:20#1] INFO -- 字幕库: 找到 'The.Hot.Spot.1990.Chs&eng.ssa', 下载量 9859
I, [2021-07-11 18:54:22#1] INFO -- : 未解压缩 /data/The.Hot.Spot.1990.REMASTERED.1080p.BluRay.x265-RARBG/zmk-21123.ssa
I, [2021-07-11 18:54:22#1] INFO -- : 电影 [狩猎], imdb: tt8244784, 已有 2 个字幕`
![image](https://user-images.githubusercontent.com/20470524/125211211-7002a680-e2d7-11eb-9a1b-bb7e3f68278a.png)

**Comment by roylez** [comment]
你再试试，我加了ssa格式支持

**Comment by fireflycao** [comment]
✌正常了！谢！
I, [2021-07-12 14:00:46#1] INFO -- : 电影 [激情沸点], imdb: tt0099797
I, [2021-07-12 14:00:47#1] INFO -- 字幕库: ---- http://zmk.pw/subs/29118.html
I, [2021-07-12 14:00:48#1] INFO -- 字幕库: 找到 'The.Hot.Spot.1990.Chs&eng.ssa', 下载量 9864
I, [2021-07-12 14:00:51#1] INFO -- : 未解压缩 /data/The.Hot.Spot.1990.REMASTERED.1080p.BluRay.x265-RARBG/zmk-21123.ssa
I, [2021-07-12 14:00:51#1] INFO -- : 重命名 zmk-21123.ssa
I, [2021-07-12 14:00:51#1] INFO -- : -> The.Hot.Spot.1990.REMASTERED.1080p.BluRay.x265-RARBG.ssa
I, [2021-07-12 14:00:51#1] INFO -- : 重命名 [zmk.pw]The.Hot.Spot.1990.Chs&amp;eng.ssa
I, [2021-07-12 14:00:51#1] INFO -- : -> The.Hot.Spot.1990.REMASTERED.1080p.BluRay.x265-RARBG.Chs&amp;eng.ssa

**Comment by fireflycao** [comment]
你好，还是时不时的停止，暂时不会在unraid的doker里面加restart: always，请问有什么解决方案吗？

**Comment by roylez** [comment]
> 你好，还是时不时的停止，暂时不会在unraid的doker里面加restart: always，请问有什么解决方案吗？

看这里：

https://forums.unraid.net/topic/61741-restart-docker-container-automatically-after-crash/?do=findComment&comment=605561

在Extra Parameters里加`--restart always`

**Comment by fireflycao** [comment]
![image](https://user-images.githubusercontent.com/20470524/126030881-1280e3fc-d214-4894-ab36-6ff97a958200.png)

**Comment by roylez** [comment]
应该是这里

**Comment by fireflycao** [comment]
设了一个小时，等会儿看结果😄

**Comment by fireflycao** [comment]
![image](https://user-images.githubusercontent.com/20470524/126049072-5c16fcd5-3269-4225-941d-7591c2b209b1.png)
Log的记录没那么多，看时间应该是已经重启程序了，'uptims 4hours','创建时间是昨天最后设定restart always的时间'
非常感谢专门为我查了unraid下的用法！🍗
