### ISSUE TITLE
卡在这里，2分钟重启一次

### ISSUE THREAD

**Issue by fireflycao** [roylez/subfinder#3]
卡在这里，2分钟重启一次
主动修改此电影字幕名称符合规则后跳过。
I, [2021-07-20 04:41:08#1] INFO -- 字幕库: 找到 '欲拒还迎 Black Venus (1983).1080p.BluRay.x264.AAC-[YTS.MX].srt', 下载量 203
I, [2021-07-20 04:41:10#1] INFO -- : 未解压缩 /data/Black.Venus.1983.DUBBED.1080p.BluRay.H264.AAC-RARBG/zmk-157151.srt
./subs.rb:292:in `_fallback_lang': invalid byte sequence in UTF-8 (ArgumentError)
from ./subs.rb:275:in `_rename_sub'
from ./subs.rb:257:in `block in rename'
from ./subs.rb:256:in `each'
from ./subs.rb:256:in `rename'
from ./subs.rb:203:in `process'
from ./subs.rb:341:in `block in run_finder'
from ./subs.rb:340:in `each'
from ./subs.rb:340:in `run_finder'
from ./subs.rb:389:in `<main>'
I, [2021-07-20 05:43:43#1] INFO -- : ....................启动 SUBS

**Comment by roylez** [comment]
字幕不是utf-8，是GBK的，大概是因为老电影。已经修复字幕语言自动检测。

**Comment by fireflycao** [comment]
谢了！



在 Roy Zuo ***@***.***>，2021年7月20日 06:54写道：

字幕不是utf-8，是GBK的，大概是因为老电影。已经修复字幕语言自动检测。
